# Generated by Django 5.0.2 on 2024-02-24 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='is_solved',
            field=models.BooleanField(default=True),
        ),
    ]
