# Generated by Django 5.0.6 on 2024-05-18 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_category_alter_post_description_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author_image',
            field=models.ImageField(null=True, upload_to='authors/'),
        ),
    ]
